package br.com.testepratico.UI;

import br.com.testepratico.Utils.funcoes;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

public final class Calendario extends javax.swing.JDialog {

    public static boolean conclui = false;

    private static Date data;
    public String dataInicial;

    /**
     * Creates new form Calendario
     *
     * @param f
     * @param modal
     */
    public Calendario(Frame f, boolean modal) {
        super(f, modal);
        this.setUndecorated(true);
        initComponents();
        confIniciais();
        teclas();
    }

    public void confIniciais() {
        funcoes f = new funcoes();

        try {
            this.setLocationRelativeTo(null);

            f.botaoTransparente(jPanel1);
        } catch (Exception e) {
            Logger.getLogger(Calendario.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public void teclas() {
        //ATALHO -> ESC
        InputMap inputMapEsc = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMapEsc.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "esc");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMapEsc);
        this.getRootPane().getActionMap().put("esc", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                data = null;
                dispose();
            }
        });

        //ATALHO -> F1
        InputMap inputMapF1 = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMapF1.put(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), "f1");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMapF1);
        this.getRootPane().getActionMap().put("f1", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                setData();
            }
        });

        //ATALHO -> F2
        InputMap inputMapF2 = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMapF2.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "f2");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMapF2);
        this.getRootPane().getActionMap().put("f2", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                data = null;
                dispose();
            }
        });

    }

    public void setData() {
        data = jCalendar1.getDate();
        conclui = true;
        this.dispose();
    }

    public String getData() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        return sdf.format(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSelecionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCabecalhoTela = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(440, 270));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/selecionarCalendario.png"))); // NOI18N
        btnSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelecionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelecionarMouseExited(evt);
            }
        });
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 130, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/bt_cancelarF2.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 130, 40));

        jCalendar1.setDate(new java.util.Date(1520878694000L));
        jCalendar1.setDecorationBackgroundColor(new java.awt.Color(240, 240, 240));
        jCalendar1.setDecorationBackgroundVisible(false);
        jCalendar1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jCalendar1.setWeekOfYearVisible(false);
        jPanel1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 200));

        jCabecalhoTela.setFont(new java.awt.Font("Open Sans Semibold", 0, 11)); // NOI18N
        jCabecalhoTela.setForeground(new java.awt.Color(255, 255, 255));
        jCabecalhoTela.setText("CONNEX ONE - ONESYS TECNOLOGIA");
        jCabecalhoTela.setToolTipText("");
        getContentPane().add(jCabecalhoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 380, 32));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/bordaFecharTela440X270.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 270));

        setBounds(0, 0, 456, 308);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        try {
            data = dataFormatada.parse(dataInicial);
            conclui = false;
            dispose();
        } catch (ParseException e) {
            Logger.getLogger(Calendario.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLayout(null);
        jPanel1.setLocation(20, 50);
        jCabecalhoTela.setVisible(true);
        jLabel1.setVisible(true);
        this.getRootPane().setOpaque(true);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        this.setSize(440, 270);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        setData();
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setIcon(new ImageIcon(getClass().getResource("/br/com/testePratico/resources/bt_cancelarF2_off.png")));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setIcon(new ImageIcon(getClass().getResource("/br/com/testePratico/resources/bt_cancelarF2.png")));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnSelecionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarMouseEntered
        btnSelecionar.setIcon(new ImageIcon(getClass().getResource("/br/com/testePratico/resources/selecionarCalendario_off.png")));
    }//GEN-LAST:event_btnSelecionarMouseEntered

    private void btnSelecionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarMouseExited
        btnSelecionar.setIcon(new ImageIcon(getClass().getResource("/br/com/testePratico/resources/selecionarCalendario.png")));
    }//GEN-LAST:event_btnSelecionarMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        funcoes f = new funcoes();
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");

        try {
            if (dataInicial == null || dataInicial.equals("") || dataInicial.equals("  /  /    ")) {
                dataInicial = f.pegarDataString();
            }

            data = dataFormatada.parse(dataInicial);
            jCalendar1.setDate(data);
        } catch (ParseException ex) {
            Logger.getLogger(Calendario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JLabel jCabecalhoTela;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
