/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.testepratico.UI;

import br.com.testepratico.Utils.funcoes;
import java.awt.Color;

/**
 *
 * @author Richard
 */
public class TelaPrincipal extends javax.swing.JFrame {

    funcoes f = new funcoes();
    Clientes clientes = new Clientes();
    Produtos produtos = new Produtos();
    Vendas vendas = new Vendas();

    /**
     * Creates new form Boleto
     */
    public TelaPrincipal() {
        this.setUndecorated(true);
        initComponents();
        configuracoesIniciais();
    }

    /**
     * MÉTODO RESPONSÁVEL POR EXECUTAR AS CONFIGURACOES INICIAIS
     */
    public void configuracoesIniciais() {
        desempenho();
        f.botaoTransparente(jPanelPrincipal);
    }

    /**
     * MÉTODO RESPONSÁVEL POR CONFIGURAR O DESEMPENHO DA TELA
     */
    public void desempenho() {
        this.setLayout(null);
        setSize(1172, 705);
        jPanelPrincipal.setLocation(69, 63);
        lblTestePratico.setVisible(true);
        lblFundo.setVisible(true);
        lblSair.setVisible(true);
        this.getRootPane().setOpaque(true);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        lblLinha1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblLinha2 = new javax.swing.JLabel();
        lblLinha3 = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        jdpTelas = new javax.swing.JDesktopPane();
        lblSair = new javax.swing.JLabel();
        lblTestePratico = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLinha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/linha.png"))); // NOI18N
        lblLinha1.setAlignmentY(1.0F);
        jPanelPrincipal.add(lblLinha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1010, 2));

        lblTitulo.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        lblTitulo.setText("TELA PRINCIPAL");
        jPanelPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 410, 23));

        lblLinha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/linha.png"))); // NOI18N
        lblLinha2.setAlignmentY(1.0F);
        jPanelPrincipal.add(lblLinha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 1010, 2));

        lblLinha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLinha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/linha-vertical.png"))); // NOI18N
        jPanelPrincipal.add(lblLinha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 60, 10, 530));

        btnCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnCliente.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/campoAzulFastFood.png"))); // NOI18N
        btnCliente.setText("CLIENTES");
        btnCliente.setBorder(null);
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClienteMouseExited(evt);
            }
        });
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 195, 50));

        btnProduto.setBackground(new java.awt.Color(255, 255, 255));
        btnProduto.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        btnProduto.setForeground(new java.awt.Color(255, 255, 255));
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/campoAzulFastFood.png"))); // NOI18N
        btnProduto.setText("PRODUTOS");
        btnProduto.setBorder(null);
        btnProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdutoMouseExited(evt);
            }
        });
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(btnProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 130, 195, 50));

        btnVenda.setBackground(new java.awt.Color(255, 255, 255));
        btnVenda.setFont(new java.awt.Font("Open Sans Extrabold", 1, 14)); // NOI18N
        btnVenda.setForeground(new java.awt.Color(255, 255, 255));
        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/campoAzulFastFood.png"))); // NOI18N
        btnVenda.setText("VENDAS");
        btnVenda.setBorder(null);
        btnVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVendaMouseExited(evt);
            }
        });
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(btnVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 210, 195, 50));

        jdpTelas.setBackground(new java.awt.Color(255, 255, 255));
        jdpTelas.setOpaque(false);

        javax.swing.GroupLayout jdpTelasLayout = new javax.swing.GroupLayout(jdpTelas);
        jdpTelas.setLayout(jdpTelasLayout);
        jdpTelasLayout.setHorizontalGroup(
            jdpTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        jdpTelasLayout.setVerticalGroup(
            jdpTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        jPanelPrincipal.add(jdpTelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 801, 554));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 63, 1032, 605));

        lblSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/X-Tela.png"))); // NOI18N
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });
        getContentPane().add(lblSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 32, 30, 30));

        lblTestePratico.setBackground(new java.awt.Color(255, 255, 255));
        lblTestePratico.setFont(new java.awt.Font("Open Sans Semibold", 0, 11)); // NOI18N
        lblTestePratico.setForeground(new java.awt.Color(255, 255, 255));
        lblTestePratico.setText("TESTE PRÁTICO - VR SOFTWARE");
        getContentPane().add(lblTestePratico, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 32, -1, 30));

        lblFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/BordaConfiguracoes.png"))); // NOI18N
        lblFundo.setMaximumSize(new java.awt.Dimension(1172, 705));
        lblFundo.setMinimumSize(new java.awt.Dimension(1172, 705));
        lblFundo.setPreferredSize(new java.awt.Dimension(1172, 705));
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseEntered
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/Resources/campoAzulFastFood_off.jpg")));
    }//GEN-LAST:event_btnClienteMouseEntered

    private void btnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseExited
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/resources/campoAzulFastFood.png")));
    }//GEN-LAST:event_btnClienteMouseExited

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        clientes.dispose();
        produtos.dispose();
        vendas.dispose();
        jdpTelas.removeAll();

        jdpTelas.add(clientes);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) clientes.getUI()).setNorthPane(null);

        clientes.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoMouseEntered
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/resources/campoAzulFastFood_off.jpg")));
    }//GEN-LAST:event_btnProdutoMouseEntered

    private void btnProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoMouseExited
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/resources/campoAzulFastFood.png")));
    }//GEN-LAST:event_btnProdutoMouseExited

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        clientes.dispose();
        produtos.dispose();
        vendas.dispose();
        jdpTelas.removeAll();

        jdpTelas.add(produtos);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) produtos.getUI()).setNorthPane(null);

        produtos.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseEntered
        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/resources/campoAzulFastFood_off.jpg")));
    }//GEN-LAST:event_btnVendaMouseEntered

    private void btnVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseExited
        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/resources/campoAzulFastFood.png")));
    }//GEN-LAST:event_btnVendaMouseExited

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        clientes.dispose();
        produtos.dispose();
        vendas.dispose();
        jdpTelas.removeAll();

        jdpTelas.add(vendas);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) vendas.getUI()).setNorthPane(null);

        vendas.setVisible(true);
    }//GEN-LAST:event_btnVendaActionPerformed

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/resources/X-Tela_off.png")));
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testepratico/resources/X-Tela.png")));
    }//GEN-LAST:event_lblSairMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnVenda;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JDesktopPane jdpTelas;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblLinha1;
    private javax.swing.JLabel lblLinha2;
    private javax.swing.JLabel lblLinha3;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblTestePratico;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
